canastaAppName: canasta
replicaCount: 1
image:
  repository: ghcr.io/canastawiki/canasta
  tag: latest
  pullPolicy: IfNotPresent
resources: {}

settingsFolder: settings/*
configFolder: config/*

sitemapDataClaimName: sitemap-data
elasticsearchDataClaimName: elasticsearch-data
