canastaAppName: canasta
replicaCount: 1
image:
  repository: ghcr.io/canastawiki/canasta
  tag: latest

canastaSettings:
  volumeName: canasta-settings
  configName: canasta-settings
  settingsFolder: settings/*

canastaConfig:
  volumeName: canasta-config
  configName: canasta-config
  configFolder: config/*

canastaEnv:
  configName: canasta-env

configVolume:
  volumeName: config-volume
  hostPath: /canasta/config-data

sitemapData:
  volumeName: sitemap-data
  claimName: sitemap-data

elasticsearchData:
  volumeName: elasticsearch
  claimName: elasticsearch-data
  