apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.canastaSettingsConfigName }}
data:
{{ (.Files.Glob .Values.settingsFolder).AsConfig | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.canastaConfigConfigName }}
data:
{{ (.Files.Glob .Values.configFolder).AsConfig | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.canastaEnvConfigName }}
data:
{{ (.Files.Glob ".env").AsConfig | indent 2 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.canastaAppName }}
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sitemapDataClaimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.elasticsearchDataClaimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.canastaAppName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.canastaAppName }}
    spec:
      containers:
      - name: web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources: {}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.canastaEnvConfigName }}
        volumeMounts:
        - mountPath: /var/www/mediawiki/w/user-extensions
          name: {{ .Values.configVolumeName }}
          subPath: ./extensions
        - mountPath: /var/www/mediawiki/w/user-skins
          name: {{ .Values.configVolumeName }}
          subPath: ./skins
        - mountPath: /mediawiki/config
          name: {{ .Values.canastaConfigConfigName }}
        - mountPath: /mediawiki/config/settings
          name: {{ .Values.canastaSettingsVolumeName }}
        - mountPath: /mediawiki/images
          name: {{ .Values.configVolumeName }}
          subPath: ./images
        - name: {{ .Values.sitemapDataVolumeName }}
          mountPath: /mediawiki/sitemap
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
        - name: {{ .Values.elasticsearchDataVolumeName }}
          mountPath: /usr/share/elasticsearch/data
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: {{ .Values.canastaConfigVolumeName }}
        configMap:
          name: {{ .Values.canastaConfigConfigName }}
      - name: {{ .Values.canastaSettingsVolumeName }}
        configMap:
          name: {{ .Values.canastaSettingsConfigName }}
      - name: {{ .Values.configVolumeName }}
        hostPath:
          path: {{ .Values.configVolumePath }}
          type: DirectoryOrCreate
      - name: {{ .Values.sitemapDataVolumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.sitemapDataClaimName }}
      - name: {{ .Values.elasticsearchDataVolumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.elasticsearchDataClaimName }}